version: "3.7"

services:
# Kong: The API Gateway
  kong:
    image: kong:2.1.0-ubuntu 
    restart: always
    env_file:
      - kong.env
    ports:
      - 8000:8000 # 接收处理 http 流量
      - 8443:8443 # 接收处理 https 流量
      #- 8001:8001 # http 管理 API
      #- 8444:8444 # https 管理 API
    depends_on:
      - postgresql

# Konga: Kong GUI
  konga:
    image: pantsel/konga:0.14.9
    restart: always
    env_file:
      - konga.env
    ports:
      - 1337:1337
    depends_on:
      - postgresql

# PostgeSQL Datebase
  postgresql:
    image: postgres:11.2
    restart: always
    env_file:
      - postgresql.env
    volumes:
      - ./pgdata:/var/lib/postgresql/data

